name: routable_annotations
description: "A package containing the necessary annotations for `routable_builder`"
version: 0.2.0
homepage: "https://github.com/WeAreAthlon/routable"

environment:
  sdk: ">=3.2.5 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
