name: routable_builder
description: "Routable is a package that provides code generation for routing in Flutter applications"
version: 1.0.0
homepage: "https://github.com/WeAreAthlon/routable"

environment:
  sdk: ">=3.2.5 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

  analyzer: ^6.7.0
  build: ^2.4.1
  glob: ^2.1.2
  source_gen: ^1.5.0

  routable_annotations: ^0.2.0
  # path: ../routable_annotations

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.9
